/**
 * Electrical power generation and storage.
 *
 * The headline advantage claimed for orbital datacenters is "free continuous
 * solar power". Two-thirds of that is true. Sunlight above the atmosphere is
 * about 1361 W/m^2 against roughly 200 W/m^2 annual-average at a good
 * terrestrial site, so the resource really is 6-7x better per unit area. But
 * "continuous" depends entirely on the orbit: a 500 km equatorial orbit is in
 * shadow for 36% of every 95-minute lap, and the battery mass needed to ride
 * through that is not small.
 *
 * A dawn-dusk sun-synchronous orbit avoids eclipse almost entirely for much of
 * the year -- which is why it keeps coming up in these proposals -- at the
 * cost of a thermal environment where the radiators never get a break.
 */

import { SOLAR_CONSTANT, AU } from './constants.js';
import { sunlitFraction, eclipseFraction, orbitalPeriod } from './orbit.js';
import { solarIrradianceAt, sunPositionEci } from './frames.js';

/**
 * Photovoltaic technologies with representative beginning-of-life numbers.
 *
 * `efficiency` is cell conversion efficiency at AM0 (the space spectrum, not
 * the AM1.5 terrestrial spectrum -- space-rated cells are always quoted lower
 * than their terrestrial equivalents for this reason).
 * `specificPower` is W/kg at the wing level including structure and mechanisms.
 * `degradationPerYear` is fractional annual loss from radiation and UV.
 */
export const SOLAR_TECH = {
  siliconSpace: {
    name: 'Space-grade silicon',
    efficiency: 0.18,
    specificPower: 50,
    degradationPerYear: 0.0275,
    arealMass: 2.5,
  },
  tripleJunction: {
    name: 'Triple-junction GaAs (rigid)',
    efficiency: 0.30,
    specificPower: 100,
    degradationPerYear: 0.005,
    arealMass: 4.0,
  },
  rosaFlexible: {
    name: 'Flexible triple-junction (ROSA-class)',
    efficiency: 0.29,
    specificPower: 150,
    degradationPerYear: 0.0075,
    arealMass: 0.9,
  },
  thinFilm: {
    name: 'Thin-film CIGS blanket',
    efficiency: 0.14,
    specificPower: 250,
    degradationPerYear: 0.02,
    arealMass: 0.4,
  },
};

/** Battery chemistries, pack-level (not cell-level) figures. */
export const BATTERY_TECH = {
  liIonSpace: {
    name: 'Space-qualified Li-ion',
    specificEnergy: 130,   // [Wh/kg] at pack level
    depthOfDischarge: 0.30, // conservative for 10+ years of LEO cycling
    roundTripEfficiency: 0.92,
    cycleLife: 60000,
  },
  liIonModern: {
    name: 'High-energy Li-ion',
    specificEnergy: 200,
    depthOfDischarge: 0.40,
    roundTripEfficiency: 0.94,
    cycleLife: 30000,
  },
  liFePO4: {
    name: 'LiFePO4 (long cycle life)',
    specificEnergy: 100,
    depthOfDischarge: 0.60,
    roundTripEfficiency: 0.95,
    cycleLife: 100000,
  },
};

/**
 * Instantaneous array output [W].
 *
 * P = S(t) * A * eta * cos(theta) * (1 - deg)^years * packing * sunlit
 *
 * `sunlit` comes from the conical shadow model, so penumbra crossings produce
 * a genuine ramp rather than a step.
 */
export function arrayPower({
  area,
  efficiency,
  incidenceAngle = 0,
  sunlit = 1,
  irradiance = SOLAR_CONSTANT,
  years = 0,
  degradationPerYear = 0.0075,
  packingFactor = 0.90,
  temperatureDerate = 1.0,
}) {
  const degradation = Math.pow(1 - degradationPerYear, years);
  return (
    irradiance *
    area *
    efficiency *
    Math.max(0, Math.cos(incidenceAngle)) *
    sunlit *
    degradation *
    packingFactor *
    temperatureDerate
  );
}

/**
 * Array area needed to deliver a required average electrical power [m^2].
 *
 * Accounts for the duty cycle: if the orbit is in sunlight only 64% of the
 * time and the batteries round-trip at 92%, the array has to be oversized by
 * roughly 1/(0.64 + 0.36*0.92) rather than by 1/0.64 -- the eclipse energy is
 * generated by the same array, just earlier.
 */
export function sizeArray({
  requiredPower,
  efficiency = 0.29,
  sunlitFractionOfOrbit = 0.64,
  roundTripEfficiency = 0.92,
  years = 5,
  degradationPerYear = 0.0075,
  packingFactor = 0.9,
  pointingEfficiency = 0.95,
  irradiance = SOLAR_CONSTANT,
  specificPower = 150,
}) {
  // Energy balance over one orbit: array runs only while sunlit and must
  // additionally charge the batteries for the eclipse portion.
  const eclipseFrac = 1 - sunlitFractionOfOrbit;
  const dutyPenalty =
    sunlitFractionOfOrbit > 0
      ? (sunlitFractionOfOrbit + eclipseFrac / roundTripEfficiency) / sunlitFractionOfOrbit
      : Infinity;

  const degradation = Math.pow(1 - degradationPerYear, years);
  const perAreaEndOfLife =
    irradiance * efficiency * degradation * packingFactor * pointingEfficiency;

  const area = (requiredPower * dutyPenalty) / perAreaEndOfLife;
  const beginningOfLifePower = area * irradiance * efficiency * packingFactor;

  return {
    area,
    dutyPenalty,
    perAreaEndOfLife,
    beginningOfLifePower,
    endOfLifePower: area * perAreaEndOfLife,
    mass: beginningOfLifePower / specificPower,
  };
}

/**
 * Battery sizing for eclipse ride-through.
 *
 * The usable fraction of a battery is small: depth of discharge is limited to
 * 30-40% to survive tens of thousands of LEO cycles, so a pack must be roughly
 * three times the energy actually needed. That factor is why battery mass is
 * often the dominant power-system mass in LEO and near-zero in a dawn-dusk
 * sun-synchronous orbit.
 */
export function sizeBattery({
  loadPower,
  eclipseDuration,
  depthOfDischarge = 0.30,
  specificEnergy = 130,
  roundTripEfficiency = 0.92,
  contingency = 1.15,
}) {
  const energyRequired = (loadPower * eclipseDuration) / 3600; // [Wh]
  const packEnergy = (energyRequired * contingency) / (depthOfDischarge * roundTripEfficiency);
  return {
    energyRequiredWh: energyRequired,
    packEnergyWh: packEnergy,
    mass: packEnergy / specificEnergy,
  };
}

/**
 * Cycles a battery endures over a mission, and whether it survives them.
 * A LEO orbit is roughly 5500 cycles per year -- 55000 over ten years, which
 * is at or beyond the qualified life of most space Li-ion at high depth of
 * discharge. GEO sees about 90 cycles a year (two eclipse seasons), a
 * completely different regime.
 */
export function batteryCycles(orbitPeriodSeconds, years, eclipseFracOfOrbit) {
  const cyclesPerYear =
    eclipseFracOfOrbit > 0 ? (365.25 * 86400) / orbitPeriodSeconds : 0;
  return {
    cyclesPerYear,
    totalCycles: cyclesPerYear * years,
  };
}

/**
 * Simulate power over one orbit, sampling the true conical shadow.
 *
 * @param {object} cfg
 * @param {number[][]} cfg.states array of ECI positions over one orbit
 * @param {number[]} cfg.sunDirection unit vector to the Sun in ECI
 * @returns {{sunlitFraction:number, eclipseDuration:number, samples:Array}}
 */
export function orbitPowerProfile({ positions, sunPosition, period, arrayConfig }) {
  const n = positions.length;
  const samples = [];
  let sunlitSum = 0;

  for (let i = 0; i < n; i++) {
    const lit = sunlitFraction(positions[i], sunPosition);
    sunlitSum += lit;
    samples.push({
      fraction: i / n,
      time: (i / n) * period,
      sunlit: lit,
      power: arrayConfig ? arrayPower({ ...arrayConfig, sunlit: lit }) : lit,
    });
  }

  const litFraction = sunlitSum / n;
  return {
    sunlitFraction: litFraction,
    eclipseFraction: 1 - litFraction,
    eclipseDuration: (1 - litFraction) * period,
    samples,
  };
}

/**
 * Analytic eclipse duration for a circular orbit at a given beta angle [s].
 * Convenience wrapper for sizing without running a full orbit sample.
 */
export function eclipseDuration(orbitRadius, betaAngle = 0) {
  const period = orbitalPeriod(orbitRadius);
  return eclipseFraction(orbitRadius, betaAngle) * period;
}

/**
 * Power distribution losses.
 *
 * Nobody gets array output to the load unscathed. At megawatt scale the
 * distribution voltage becomes a real design driver: 120 V at 10 MW is 83000
 * amperes, which is not a bus, it is a busbar the size of a person. Real
 * high-power concepts run kilovolt distribution for this reason, which brings
 * its own problem -- Paschen breakdown in the residual plasma of LEO.
 */
export function distributionLosses({ power, busVoltage = 120, cableLength = 50, efficiencyPmad = 0.93 }) {
  const current = power / busVoltage;
  return {
    current,
    pmadEfficiency: efficiencyPmad,
    deliveredPower: power * efficiencyPmad,
    lostPower: power * (1 - efficiencyPmad),
    // Conductor cross-section for a 1% resistive loss at 2 A/mm^2 current
    // density, copper. Purely indicative of the scale of the problem.
    conductorCrossSectionMm2: current / 2,
    conductorMassKg: (current / 2) * 1e-6 * cableLength * 8960 * 2,
    warning:
      current > 5000
        ? `Bus current of ${Math.round(current)} A at ${busVoltage} V is impractical; raise the distribution voltage.`
        : null,
  };
}
